info:
    license:
        name: "Apache 2.0"
        url: "http://www.apache.org/licenses/LICENSE-2.0.html"
    title: "Frontend View State"
    version: v1.0
openapi: 3.0.1
paths:
    "/active-view/{activeViewId}":
        get:
            parameters:
                - in: path
                  name: activeViewId
                  required: true
                  schema:
                      type: string
                - in: query
                  name: plid
                  schema:
                      format: int64
                      type: integer
                - in: query
                  name: portletId
                  schema:
                      type: string
            responses:
                200:
                    content:
                        application/json:
                            schema:
                                type: object
                        application/xml:
                            schema:
                                type: object
                    description:
                        ""
            tags: ["ActiveView"]
        put:
            parameters:
                - in: path
                  name: activeViewId
                  required: true
                  schema:
                      type: string
                - in: query
                  name: plid
                  schema:
                      format: int64
                      type: integer
                - in: query
                  name: portletId
                  schema:
                      type: string
            requestBody:
                content:
                    application/json:
                        schema:
                            type: string
                    application/xml:
                        schema:
                            type: string
            responses:
                200:
                    content:
                        application/json:
                            schema:
                                type: object
                        application/xml:
                            schema:
                                type: object
                    description:
                        ""
            tags: ["ActiveView"]