components:
    schemas:
        ObjectDefinition:
            properties:
                actions:
                    additionalProperties:
                        additionalProperties:
                            type: string
                        type: object
                    readOnly: true
                    type: object
                dateCreated:
                    format: date
                    readOnly: true
                    type: string
                dateModified:
                    format: date
                    readOnly: true
                    type: string
                id:
                    format: int64
                    readOnly: true
                    type: integer
                name:
                    type: string
                objectFields:
                    items:
                        $ref: "#/components/schemas/ObjectField"
                    type: array
            type: object
        ObjectField:
            properties:
                dateCreated:
                    format: date
                    readOnly: true
                    type: string
                dateModified:
                    format: date
                    readOnly: true
                    type: string
                id:
                    format: int64
                    readOnly: true
                    type: integer
                indexed:
                    type: boolean
                indexedAsKeyword:
                    type: boolean
                indexedLanguageId:
                    type: string
                name:
                    type: string
                type:
                    type: string
info:
    license:
        name: "Apache 2.0"
        url: "http://www.apache.org/licenses/LICENSE-2.0.html"
    title: "Object"
    version: v1.0
openapi: 3.0.1
paths:
    "/object-definitions":
        get:
            operationId: getObjectDefinitionsPage
            parameters:
                - in: query
                  name: page
                  schema:
                      type: integer
                - in: query
                  name: pageSize
                  schema:
                      type: integer
                - in: header
                  name: Accept-Language
                  schema:
                      type: string
            responses:
                200:
                    content:
                        application/json:
                            schema:
                                items:
                                    $ref: "#/components/schemas/ObjectDefinition"
                                type: array
                        application/xml:
                            schema:
                                items:
                                    $ref: "#/components/schemas/ObjectDefinition"
                                type: array
                    description:
                        ""
            tags: ["ObjectDefinition"]
        post:
            operationId: postObjectDefinition
            requestBody:
                content:
                    application/json:
                        schema:
                            $ref: "#/components/schemas/ObjectDefinition"
                    application/xml:
                        schema:
                            $ref: "#/components/schemas/ObjectDefinition"
            responses:
                200:
                    content:
                        application/json:
                            schema:
                                $ref: "#/components/schemas/ObjectDefinition"
                        application/xml:
                            schema:
                                $ref: "#/components/schemas/ObjectDefinition"
                    description:
                        ""
            tags: ["ObjectDefinition"]
    "/object-definitions/{objectDefinitionId}":
        delete:
            operationId: deleteObjectDefinition
            parameters:
                - in: path
                  name: objectDefinitionId
                  required: true
                  schema:
                      format: int64
                      type: integer
            responses:
                204:
                    content:
                        application/json: {}
                        application/xml: {}
                    description:
                        ""
            tags: ["ObjectDefinition"]
        get:
            operationId: getObjectDefinition
            parameters:
                - in: path
                  name: objectDefinitionId
                  required: true
                  schema:
                      format: int64
                      type: integer
            responses:
                200:
                    content:
                        application/json:
                            schema:
                                $ref: "#/components/schemas/ObjectDefinition"
                        application/xml:
                            schema:
                                $ref: "#/components/schemas/ObjectDefinition"
                    description:
                        ""
            tags: ["ObjectDefinition"]